name: Validate Caddyfile

on:
  push:
    branches: [ master, main ]
    paths: [ 'Caddyfile' ]
  pull_request:
    branches: [ master, main ]
    paths: [ 'Caddyfile' ]
  workflow_dispatch:

jobs:
  validate-caddy:
    name: Validate Caddyfile Configuration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Caddy
      run: |
        sudo apt update
        sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
        sudo apt update
        sudo apt install caddy
        
    - name: Validate Caddyfile
      run: |
        echo "Validating Caddyfile configuration..."
        caddy validate --config ./Caddyfile
        echo "✅ Caddyfile is valid!"
        
    - name: Format check (optional)
      run: |
        echo "Checking Caddyfile formatting..."
        # Create a temporary formatted file to compare
        cp Caddyfile Caddyfile.tmp
        caddy fmt --overwrite Caddyfile.tmp
        if ! diff -q Caddyfile Caddyfile.tmp > /dev/null; then
          echo "⚠️  Caddyfile could be formatted better. Run 'caddy fmt --overwrite' to fix."
          echo "Differences:"
          diff Caddyfile Caddyfile.tmp || true
        else
          echo "✅ Caddyfile formatting is good!"
        fi
        rm -f Caddyfile.tmp
